AWSTemplateFormatVersion: '2010-09-09'
Description: >-
  AWS Serverless stack for Port integration. Creates an EventBridge rule that routes
  AWS events to an SQS queue and a Lambda function that processes the queue and
  forwards enriched events to Port via a single ingest webhook.

Parameters:
  QueueName:
    Type: String
    Default: port-aws-events-queue
    Description: Name of the SQS queue
  LambdaFunctionName:
    Type: String
    Default: port-aws-event-processor
  LambdaRuntime:
    Type: String
    Default: python3.11
  Handler:
    Type: String
    Default: handler.lambda_handler
  PortWebhookUrl:
    Type: String
    Description: The Port ingest webhook URL that the Lambda will POST to (include schema 'https://')

Resources:
  EventsQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Ref QueueName

  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub "${LambdaFunctionName}-execution-role-${AWS::StackName}"
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: SqsAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - sqs:ReceiveMessage
                  - sqs:DeleteMessage
                  - sqs:GetQueueAttributes
                Resource: !GetAtt EventsQueue.Arn

  PortEventsProcessorFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Ref LambdaFunctionName
      Runtime: !Ref LambdaRuntime
      Handler: !Ref Handler
      Role: !GetAtt LambdaExecutionRole.Arn
      Timeout: 30
      Environment:
        Variables:
          PORT_WEBHOOK_URL: !Ref PortWebhookUrl
    Code:
    ZipFile: |
      import json
      import os
      import logging
      import time
      from urllib import request

      logger = logging.getLogger()
      logger.setLevel(logging.INFO)

      PORT_WEBHOOK = os.environ.get('PORT_WEBHOOK_URL')

      def post_to_port(body_bytes: bytes, headers: dict) -> tuple[int, str]:
        req = request.Request(PORT_WEBHOOK, data=body_bytes, headers=headers, method='POST')
        with request.urlopen(req, timeout=10) as resp:
          return resp.getcode(), resp.read().decode('utf-8')

      def _build_minimal_entity_from_event(payload: dict) -> dict:
        identifier = None
        if isinstance(payload.get('detail'), dict):
          detail = payload.get('detail')
          identifier = detail.get('resource') or detail.get('requestParameters', {}).get('bucketName')
          if not identifier:
            identifier = payload.get('id') or payload.get('detail', {}).get('arn')
        identifier = identifier or payload.get('id') or f"aws-event-{int(time.time()*1000)}"
        title = payload.get('detail-type') or payload.get('source') or identifier
        return {
          'identifier': identifier,
          'title': title,
          'blueprint': 'awsEvent',
          'properties': {'event': payload},
        }

      def lambda_handler(event, context):
        logger.info('Received event with %d records', len(event.get('Records', [])))
        for rec in event.get('Records', []):
          body = rec.get('body')
          if not body:
            continue
          try:
            payload = json.loads(body)
          except Exception:
            payload = {'raw': body}

          if isinstance(payload, dict) and 'blueprint' in payload and 'identifier' in payload:
            entity = payload
          else:
            entity = _build_minimal_entity_from_event(payload)

          body_bytes = json.dumps(entity).encode('utf-8')
          headers = {'Content-Type': 'application/json'}
          try:
            status, resp_text = post_to_port(body_bytes, headers)
            logger.info('Posted entity to Port, status=%s, identifier=%s', status, entity.get('identifier'))
          except Exception:
            logger.exception('Error posting to Port')

  EventBridgeToSqsRule:
    Type: AWS::Events::Rule
    Properties:
      Description: "Route selected AWS events to SQS queue for Port processing"
      EventPattern:
        source: ["aws.ec2", "aws.s3", "aws.rds", "aws.sqs"]
      Targets:
        - Arn: !GetAtt EventsQueue.Arn
          Id: SqsTarget
          SqsParameters:
            MessageGroupId: "port-events" # For FIFO queue; ignored for standard queues

  SqsQueuePolicy:
    Type: AWS::SQS::QueuePolicy
    Properties:
      Queues:
        - !Ref EventsQueue
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal: '*'
            Action: "sqs:SendMessage"
            Resource: !GetAtt EventsQueue.Arn
            Condition:
              ArnEquals:
                aws:SourceArn: !Sub arn:aws:events:${AWS::Region}:${AWS::AccountId}:rule/*

  EventSourceMapping:
    Type: AWS::Lambda::EventSourceMapping
    Properties:
      BatchSize: 10
      EventSourceArn: !GetAtt EventsQueue.Arn
      FunctionName: !GetAtt PortEventsProcessorFunction.Arn
      Enabled: True

Outputs:
  QueueUrl:
    Description: URL for the SQS queue
    Value: !Ref EventsQueue
  LambdaName:
    Description: Lambda function name
    Value: !Ref PortEventsProcessorFunction
